=== davudmurtazin/Task7/src/menuSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 	xmlns="http://www.w3.org/2001/XMLSchema"
		    targetNamespace="http://www.davud.org/menuList"
		    xmlns:tns="http://www.davud.org/menuList"
		    elementFormDefault="qualified">
	
	<element name="menuList">
		<complexType>
			<sequence>
				<element name="dishSelection" type="tns:DishSelection" minOccurs="1" maxOccurs="12" />
			</sequence>
		</complexType>
	</element>

	<complexType name="DishSelection">
		<sequence>
			<element name="dish" type="tns:dish" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="dishType" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="coldSnacks"></enumeration>
					<enumeration value="hotSnacks"></enumeration>
					<enumeration value="breakfastMeal"></enumeration>
					<enumeration value="salads"></enumeration>
					<enumeration value="soups"></enumeration>
					<enumeration value="fishMeal"></enumeration>
					<enumeration value="meatMeal"></enumeration>
					<enumeration value="garnishes"></enumeration>
					<enumeration value="barbecues"></enumeration>
					<enumeration value="mealFromChef"></enumeration>
					<enumeration value="attachment"></enumeration>
					<enumeration value="desserts"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="dish">
		<sequence>
			<element name="photo" type="anyURI" />
			<element name="title" type="string" />
			<element name="specification" type="tns:specification" />
		</sequence>
	</complexType>

	<complexType name="specification">
		<sequence>
			<element name="descriptionSelection" type="tns:descriptionSelection"/>
			<element name="portionSelection" type="tns:portionSelection"/>
			<element name="priceSelection" type="tns:priceSelection"/>
		</sequence>
	</complexType>
	
	<complexType name="descriptionSelection">
		<sequence>
			<element name="description" type="string"/>
		</sequence>
	</complexType>
	
	<complexType name="portionSelection">
		<sequence>
			<element name="portion" type="int"/>
		</sequence>
	</complexType>
	
	<complexType name="priceSelection">
		<sequence>
			<element name="price" type="int"/>
		</sequence>
	</complexType>
</schema>

=== davudmurtazin/Task7/src/dishes.xml
<?xml version="1.0" encoding="UTF-8"?>

<menuList 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	    xmlns="http://www.davud.org/menuList"
		xsi:schemaLocation="http://www.davud.org/menuList menuSchema.xsd">
	<dishSelection dishType="coldSnacks">
		<dish>
			<photo>\menu\fish.png</photo>
			<title>Ассорти рыбное</title>
			<specification>
				<descriptionSelection>
					<description>Слабосоленная форель, семга</description>
				</descriptionSelection>
				<portionSelection>
					<portion>100</portion>
					<portion>20</portion>
					<portion>15</portion>>
				</portionSelection>
				<priceSelection>
					<price/>
				</priceSelection>
			</specification>
		</dish>	
		<dish>
			<photo>\menu\fish1.png</photo>
			<title>Тарталетки с красной икрой</title>
			<specification>
				<descriptionSelection>
					<description>Тарталетки с красной икрой</description>
				</descriptionSelection>
				<portionSelection>
					<portion>60</portion>
					<portion>50</portion>
				</portionSelection>
				<priceSelection>
					<price/>
				</priceSelection>
			</specification>
		</dish>	
		<dish>
			<photo>\menu\snacks.png</photo>
			<title>Закуски по-русски</title>
			<specification>
				<descriptionSelection>
					<description>Кусочки атлантической сельди с отварным картофелем, леком, лимоном и зеленью</description>
				</descriptionSelection>
				<portionSelection>
					<portion>70</portion>
					<portion>50</portion>
					<portion>2</portion>
					<portion>10</portion>
				</portionSelection>
				<priceSelection>
					<price/>
				</priceSelection>
			</specification>
		</dish>	
	</dishSelection>
	<dishSelection dishType="hotSnacks">
		<dish>
			<photo>\menu\mashrooms.png</photo>
			<title>Либио с шампиньонами</title>
			<specification>
				<descriptionSelection>
					<description>Фасоль с шампиньонами и грецким орехом</description>
				</descriptionSelection>
				<portionSelection>
					<portion>150</portion>
					<portion>5</portion>
				</portionSelection>
				<priceSelection>
					<price>105</price>
				</priceSelection>
			</specification>
		</dish>	
		<dish>
			<photo>\menu\julienne.png</photo>
			<title>Жульен</title>
			<specification>
				<descriptionSelection>
					<description>С курицей</description>
					<description>С грибами</description>
				</descriptionSelection>
				<portionSelection>
					<portion>120</portion>
					<portion>1</portion>
				</portionSelection>
				<priceSelection>
					<price>145</price>
					<price>155</price>
				</priceSelection>
			</specification>
		</dish>	
		<dish>
			<photo>\menu\ahtamar.png</photo>
			<title>Ахтамар мясной</title>
			<specification>
				<descriptionSelection>
					<description>Колбаса, ветчина, буженина, сыр, запеченные на мангале в лаваше</description>
				</descriptionSelection>
				<portionSelection>
					<portion>1</portion>
				</portionSelection>
				<priceSelection>
					<price>165</price>
				</priceSelection>
			</specification>
		</dish>	
	</dishSelection>
	<dishSelection dishType="breakfastMeal">
		<dish>
			<photo>\menu\eggs.png</photo>
			<title>Глазунья</title>
			<specification>
				<descriptionSelection>
					<description>2 яйца (на выбор: ветчина, сыр, помидоры)</description>
				</descriptionSelection>
				<portionSelection>
					<portion>150</portion>
				</portionSelection>
				<priceSelection>
					<price/>
				</priceSelection>
			</specification>
		</dish>	
		<dish>
			<photo>\menu\omelet.png</photo>
			<title>Омлет</title>
			<specification>
				<descriptionSelection>
					<description> </description>
				</descriptionSelection>
				<portionSelection>
					<portion>100</portion>
				</portionSelection>
				<priceSelection>
					<price> </price>
				</priceSelection>
			</specification>
		</dish>	
		<dish>
			<photo>\menu\pancakes.png</photo>
			<title>Блинчики с мясом</title>
			<specification>
				<descriptionSelection>
					<description>Жаренные блинчики с мясом</description>
				</descriptionSelection>
				<portionSelection>
					<portion>150</portion>
				</portionSelection>
				<priceSelection>
					<price> </price>
				</priceSelection>
			</specification>
		</dish>	
	</dishSelection>
</menuList>
